# Generated by Django 2.2.2 on 2019-06-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_model.Topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
