# Generated by Django 2.2.5 on 2019-09-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0003_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
